### ISSUE TITLE
JOSS - Missing API documentation

### ISSUE THREAD

**Issue by mnarayan** [maxrousseau/pfla#11]
The readme points to documentation link here https://pfla.readthedocs.io/en/latest/overview.html. 
However, I don't see any API documentation of the core functions implemented in `face_detect.py` and `annotate.py`. These strike me as the core functionality. 

https://github.com/maxrousseau/pfla/blob/master/pfla/fcn/annotate.py
https://github.com/maxrousseau/pfla/blob/master/pfla/fcn/face_detect.py

I would ensure that the classes and key functions support additional documentation give both a few sentences about its purpose, input and output arguments. Use an example from scikit-learn such as http://scikit-learn.org/stable/modules/generated/sklearn.feature_extraction.image.extract_patches_2d.html#sklearn.feature_extraction.image.extract_patches_2d as a guide.

**Comment by maxrousseau** [comment]
Did you look at the module index?
https://pfla.readthedocs.io/en/latest/genindex.html

All classes and functions should be automatically documented by sphinx.

**Comment by mnarayan** [comment]
Thanks, can you point to that in the sidebar as well?

**Comment by maxrousseau** [comment]
Just added it to the sidebar. Thanks.
