### ISSUE TITLE
JOSS - Improve example usage

### ISSUE THREAD

**Issue by mnarayan** [maxrousseau/pfla#12]
Currently the README provides the following usage example
https://github.com/maxrousseau/pfla#usage

However, it doesn't clearly show how the data/images need to be organized in order for this to work. Is there an example dataset that comes with the package? If so, can you modify the usage example to clearly explain
- [x] How the input data is expected to be organized using your example dataset
- [x] Incorporate the example dataset into the usage example

**Comment by maxrousseau** [comment]
Hello,
I added test directories to the repository do demonstrate how to use the package.
Let me know if we can close.
Thank you

**Comment by mnarayan** [comment]
LGTM
