### ISSUE TITLE
JOSS - Add Community Guidelines

### ISSUE THREAD

**Issue by mnarayan** [maxrousseau/pfla#5]
Can you provide a Contribution.md file with clear guidelines for how someone can 

 1) Contribute to the software 
2) Report issues or problems with the software 
3) Seek support

See example guide here: 
https://help.github.com/articles/setting-guidelines-for-repository-contributors/

**Comment by maxrousseau** [comment]
Hello,

I added a contribute.md file to address this problem (https://github.com/maxrousseau/pfla/blob/master/contributing.md), and a reference to it in the README.

Let me know if this is satisfactory.

Thank you.

**Comment by mnarayan** [comment]
Great!
