### ISSUE TITLE
JOSS - Incomplete Software Paper 

### ISSUE THREAD

**Issue by mnarayan** [maxrousseau/pfla#6]
Hello, 

Some enhancements to https://github.com/maxrousseau/pfla/blob/master/paper/paper.md are needed. 

Can you also provide a laymen's description of what types of inputs/outputs your toolbox provides? Despite knowing something about statistical shape analysis, I'm not able to follow exactly what the software can do for me. If you can add a small figure, even better! Some important information is buried in the middle. On pg. 2 you describe M_patient and V_patient. I would try to make this section even simpler/clearer. 

Can you add references to the specific solvers and algorithms used for Generalized Procrustes Analysis in your software? 
Fix the references for Dryden 2017 to point to the specific package url 
https://cran.r-project.org/web/packages/shapes/shapes.pdf

And the corresponding book that discusses the algorithms 
e Dryden, I.L. and Mardia, K.V. (2016). Statistical shape analysis,
with Applications in R (2nd Edition), John Wiley and Sons.

**Comment by maxrousseau** [comment]
Thank you for your feedback.

I have:
- restructured the paper to make it easier to follow
- added a better general description of the use case of the software and a figure to illustrate it
- rewrote and simplified the mathematics notation
- added references to the statistical analysis section (and modified the URL mentioned above)

Let me know if those modifications were satisfactory.

Thank you

**Comment by mnarayan** [comment]
Much more readable! This is good.
