### ISSUE TITLE
JOSS: Review install guideline

### ISSUE THREAD

**Issue by glemaitre** [maxrousseau/pfla#7]
Couple of points to address:

* I don't think that you depend on argparse since it is in the standard library.
* You should as well mention that you support Python 3.5+
* Is there a reason for the package to not work cross-platform. All packages installed with conda should work under MacOS and Windows.
* I would remove the `install_requires` from the `setup.py` since the `opencv` package will be installed from pip even if it was installed with `conda`. You can instead create a `requirements.txt` for the PyPi folks.
* The statement `Place the downloaded ...` is not correct for all environment and depending of the way that you installed the software.

**Comment by maxrousseau** [comment]
These issues have been resolved:
- removed argparse
- it has not been tested cross platform which is why i did not include it
- i removed install_requires and replaced it with requirements.txt
- fetcher.py function replaces the large file download
can we close?

**Comment by arokem** [comment]
@glemaitre : can this issue be closed?

**Comment by maxrousseau** [comment]
@glemaitre, @arokem: I believe this has been adressed, closing.
