### ISSUE TITLE
JOSS - Large file location

### ISSUE THREAD

**Issue by glemaitre** [maxrousseau/pfla#8]
It is user unfriendly to ask to copy some specific data which moreover would be placed at different location depending of the system and the way the package is installed.

A solution for this is to write a fetcher which will fetch the data from a location (you can use zenodo to host the data for instance) and download the data to a package home folder.

For instance, scikit-learn create by default a `~/scikit_learn_data` which can be set to another location by the user as well. It will make the package more flexible. For instance, you can refer to:
https://github.com/scikit-learn/scikit-learn/blob/master/sklearn/datasets/california_housing.py

**Comment by maxrousseau** [comment]
I have just added a fetcher function that checks if the file is present and downloads it if it is not.
Let me know if we can close.

**Comment by arokem** [comment]
@glemaitre : can this issue be closed?

**Comment by maxrousseau** [comment]
@glemaitre, @arokem: the problem raised here has been addressed. Thank you, closing.
