### ISSUE TITLE
JOSS Unit tests

### ISSUE THREAD

**Issue by glemaitre** [maxrousseau/pfla#9]
I have some issues with the tests:

* The test should be run using `pytest` instead of just `python`
* The unit test are making some appriori on where the data are:

```python
for p in sys.path:                                                                   
    if 'packages' in p:                                                              
        mod_path = p                                                                 
mod_path = mod_path + "/pfla"  
```

It will not work in the package is installed in developer mode (`pip install -e .`)

You need to use something like `dirname(__file__)` to get the current path and relatively find the testing data.

**Comment by glemaitre** [comment]
Also you should use `os.path.join` instead of string concatenation when manipulating path. It will work across platform while the latter is not robust.

**Comment by glemaitre** [comment]
This last issue is also present in the package itself (e.g. `face_detect.py`) The fetcher would solve this issue.

**Comment by maxrousseau** [comment]
I changed all path concatenations to use ```os.path.join```.
The developer mode install should works now.

I was not able to migrate testing to pytest, is this absolutely necessary?

**Comment by arokem** [comment]
I'd say that for the purpose of the JOSS paper, there is no requirement to move your testing to pytest.

@glemaitre : can this issue be closed?

**Comment by maxrousseau** [comment]
@arokem, @glemaitre: I will close this issue. Thank you for your feedback.
